### ISSUE TITLE
función en el mid para obtener plan de adquisiciones separando por fuentes de recursos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_mid#4]
se debe de completar primero el  [issue 17 de pan adquisiciones crud](https://github.com/udistrital/plan_adquisiciones_crud/issues/17)

se requiere realizar un endpoint en el cual se puedan obtener los registros de un plan de cuentas contables ordenados por el rubro, adicionalmente debe ir separado por su fuente de recurso, esta fuente de recurso se indica por el segundo nivel del arbol de rubros. Estos niveles se pueden ver en el aplicativo de [plan_adquisiciones_cliente](https://github.com/udistrital/plan_adquisiciones_cliente) en la función de crear lineamientos.

La fuente de recurso se define por 2 segmentos de números por ejemplo `3-01` o `3-03`.

para lograr ello el proceso recomendado es el siguiente

- [x] ingrese un plan de adqucisiones, ya sea desde postman o desde el mismo swagger (se recomienda postman ya que se puede compartiir las peticiones con sus datos incluidos) e ingresar registros de prueba de la tabla registros plan_adquicisiones ( en caso que ya este listas esas funciones del cliente se le comunicara para que pieda usarlo) 

- [x] realizar una petición al [api crud](https://github.com/udistrital/plan_adquisiciones_crud) (se recomienda usar swagger) usando en el campo de query el id del plan de adquicisiones, en el campo de sortby usan `rubro_id` y en el campo de order usar `asc` con ello lo obtendar ordenado.

- [ ] en base a lo anterior debe de separa por los primeros 2 segmentos del rubro_id , de tal manera que queden separados en diferentes categorias segun su rubro, la categoría debe de tener el nombre del rubro, para ello debe de consultar a `plan_cuentas_mongo_crud` para obtener el detalle de ese rubro.

###  tener en cuenta

- la url principal de las demas apis debe ir en variables de entorno.
- se recomienda tener vpn para consultar el api de `plan_cuentas_mongo_crud`
- si el api no esta dockerizado por favor dockerizarlo.
- debe de bajar al local el api de `plann_adquicisiones_crud`
- los controladores **No** deben de tener lógica de procesamiento de datos ( esto lo puede hacer en los modelos)
- para tener buenas practicas se recomienda que una función solo realice un proceso de logica con el fin de debuguear la logica mas fácil, permitir reutilización y permitir fácil extensión de la lógica.
- se debe de manejar errores.
- tanto la respuesta de los datos como la respuesta del error debe ser en json

**Comment by NRDaza** [comment]
Ejemplo resultado EndPoint
![datos](https://user-images.githubusercontent.com/34488581/100363948-70119880-2fcb-11eb-8f28-fc0b4d1cc257.png)

**Comment by NRDaza** [comment]
```json
{
  "Type": "OK",
  "Code": "200",
  "Body": {
    "Rubro: 301": [
      {
        "Activo": true,
        "AreaFuncional": 0,
        "CentroGestor": 0,
        "FechaCreacion": "2020-11-25 13:22:38.440212 +0000 +0000",
        "FechaEstimadaFin": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaEstimadaInicio": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaModificacion": "2020-11-25 13:22:38.440335 +0000 +0000",
        "Id": 22,
        "MetaId": "string",
        "PlanAdquisicionesId": {
          "Activo": true,
          "Descripcion": "pruebaFinal",
          "FechaCreacion": "2020-11-25 13:21:57.671624 +0000 +0000",
          "FechaModificacion": "2020-11-25 13:21:57.674089 +0000 +0000",
          "Id": 5,
          "Publicado": true,
          "Vigencia": 0
        },
        "ProductoId": "string",
        "ResponsableId": 0,
        "RubroId": "3-01-1"
      }
    ],
    "Rubro: 302": [
      {
        "Activo": true,
        "AreaFuncional": 0,
        "CentroGestor": 0,
        "FechaCreacion": "2020-11-25 13:22:46.96571 +0000 +0000",
        "FechaEstimadaFin": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaEstimadaInicio": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaModificacion": "2020-11-25 13:22:46.965793 +0000 +0000",
        "Id": 23,
        "MetaId": "string",
        "PlanAdquisicionesId": {
          "Activo": true,
          "Descripcion": "pruebaFinal",
          "FechaCreacion": "2020-11-25 13:21:57.671624 +0000 +0000",
          "FechaModificacion": "2020-11-25 13:21:57.674089 +0000 +0000",
          "Id": 5,
          "Publicado": true,
          "Vigencia": 0
        },
        "ProductoId": "string",
        "ResponsableId": 0,
        "RubroId": "3-02-1"
      }
    ],
    "Rubro: 303": [
      {
        "Activo": true,
        "AreaFuncional": 0,
        "CentroGestor": 0,
        "FechaCreacion": "2020-11-25 13:22:51.702489 +0000 +0000",
        "FechaEstimadaFin": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaEstimadaInicio": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaModificacion": "2020-11-25 13:22:51.702594 +0000 +0000",
        "Id": 24,
        "MetaId": "string",
        "PlanAdquisicionesId": {
          "Activo": true,
          "Descripcion": "pruebaFinal",
          "FechaCreacion": "2020-11-25 13:21:57.671624 +0000 +0000",
          "FechaModificacion": "2020-11-25 13:21:57.674089 +0000 +0000",
          "Id": 5,
          "Publicado": true,
          "Vigencia": 0
        },
        "ProductoId": "string",
        "ResponsableId": 0,
        "RubroId": "3-03-1"
      }
    ],
    "Rubro: 305": [
      {
        "Activo": true,
        "AreaFuncional": 0,
        "CentroGestor": 0,
        "FechaCreacion": "2020-11-25 13:22:57.613212 +0000 +0000",
        "FechaEstimadaFin": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaEstimadaInicio": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaModificacion": "2020-11-25 13:22:57.613293 +0000 +0000",
        "Id": 26,
        "MetaId": "string",
        "PlanAdquisicionesId": {
          "Activo": true,
          "Descripcion": "pruebaFinal",
          "FechaCreacion": "2020-11-25 13:21:57.671624 +0000 +0000",
          "FechaModificacion": "2020-11-25 13:21:57.674089 +0000 +0000",
          "Id": 5,
          "Publicado": true,
          "Vigencia": 0
        },
        "ProductoId": "string",
        "ResponsableId": 0,
        "RubroId": "3-05-1"
      },
      {
        "Activo": true,
        "AreaFuncional": 0,
        "CentroGestor": 0,
        "FechaCreacion": "2020-11-25 13:23:01.342615 +0000 +0000",
        "FechaEstimadaFin": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaEstimadaInicio": "2020-11-23 11:29:58.094423 +0000 +0000",
        "FechaModificacion": "2020-11-25 13:23:01.342694 +0000 +0000",
        "Id": 27,
        "MetaId": "string",
        "PlanAdquisicionesId": {
          "Activo": true,
          "Descripcion": "pruebaFinal",
          "FechaCreacion": "2020-11-25 13:21:57.671624 +0000 +0000",
          "FechaModificacion": "2020-11-25 13:21:57.674089 +0000 +0000",
          "Id": 5,
          "Publicado": true,
          "Vigencia": 0
        },
        "ProductoId": "string",
        "ResponsableId": 0,
        "RubroId": "3-05-2"
      }
    ]
  }
}
```

**Comment by BOTOOM** [comment]
@NRDaza me agrada el como esta, solo una pequeña modificación ya que se sabe que los datos en este caso son del plan numero 5 , entonces el objeto llamado `PlanAdquisicionesId` sobra y ademas esta duplicado por ende es peso extra en la petición, debido a ello porfa eliminalo en la respuesta que se le manda al cliente, eso se puede hacer durante el procesamiento de los datos

adicionalmente había otro endpoint que responde ese?

adicionalmente ya es por molestar pero es por temas de documentación y y buenas practicas. El endpoint dice fuentes pero no es explicito a lo que hace por ende colocale algo como `registro organizados por rubro` o algo asi   (pero que se pueda intuir que onda con ese endpoint, no necesariamente tiene que ser ese nombre), adicionalmente en la descripcion sel swagger explicar eso

aplica también para el otro endpoint que dice `planAdquisicion`
