### ISSUE TITLE
ajuste para integracion con las nuevas adiciones en el crud

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_mid#40]

**Comment by ManuelMurillo** [comment]
Los ajustes a realizar en el mid, una vez ajustado el CRUD del plan de adquisiciones son:

- [ ] Agregar modelos para Gestionar las tablas de Metas asociadas (Creación, Lectura y Actualización)
- [ ] Agregar modelos para Gestionar las tablas de Productos asociados (Creación, Lectura y Actualización)
- [ ] Agregar Funciones para Crear Leer y actualizar registros de Funcionamiento
- [ ] Seccionar las funciones de Creación, Actualización y lectura para poder realizar registro de inversión y registro de funcionamiento en el mismo endpoint
- [ ] Agregar La gestión de los registros de Metas asociadas al Registro de inversión
- [ ] Agregar la gestión de los registros de Productos asociados al registro de Inversión
- [ ] Ajustar la funcion de lectura general del plan de adquisiciones para agrupar los datos de acuerdo a los mockups
